/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package name.upton.zest.thrift.log;



public enum SubscribeFlag implements org.apache.thrift.TEnum {
  ADD(0),
  MODIFY(1),
  DELETE(2);

  private final int value;

  private SubscribeFlag(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SubscribeFlag findByValue(int value) { 
    switch (value) {
      case 0:
        return ADD;
      case 1:
        return MODIFY;
      case 2:
        return DELETE;
      default:
        return null;
    }
  }
}
